import { ImageName } from "./imageNames.ts";

export const IMAGE_NAMES = [
  ImageName.Aftrekkendeman,
  ImageName.AutoOgenEnlijnen,
  ImageName.Handenoplichaam,
  ImageName.AutoOgen,
  ImageName.Badkamer,
  ImageName.Boos,
  ImageName.Cheers,
  ImageName.Drankjesdoen,
  ImageName.EngbosFiets,
  ImageName.GeestVanDeHarrasor,
  ImageName.HandenEnthuis,
  ImageName.HandenHuilen,
  ImageName.Hoofd4bij5,
  ImageName.Img2942,
  ImageName.Img2943,
  ImageName.Indetram,
  ImageName.Ingebroken,
  ImageName.Ingebroken2,
  ImageName.Kruis1,
  ImageName.ManAutoLijnen,
  ImageName.Man,
  ImageName.Manogen,
  ImageName.Ogenman,
  ImageName.Onemore,
  ImageName.Rits,
  ImageName.Rodeman,
  ImageName.Tekst,
  ImageName.UntitledArtwork94,
  ImageName.ViezeMan,
  ImageName.Viezevrouw,
  ImageName.Vrouviezpsd,
  ImageName.Womendoorgaan,
  ImageName.Youlikethis
];

