export const ImageName = {
  Aftrekkendeman: "aftrekkendeman",
  AutoOgenEnlijnen: "auto-ogen-enlijnen",
  AutoOgen: "auto-ogen",
  Badkamer: "badkamer",
  Boos: "boos",
  Cheers: "cheers",
  Drankjesdoen: "drankjesdoen",
  EngbosFiets: "engbos-fiets",
  GeestVanDeHarrasor: "geest-van-de-harrasor",
  HandenEnthuis: "handen-enthuis",
  HandenHuilen: "handen-huilen",
  Handenoplichaam: "handenoplichaam",
  Hoofd4bij5: "hoofd4bij5",
  Img2942: "img-2942",
  Img2943: "img-2943",
  Indetram: "indetram",
  Ingebroken: "ingebroken",
  Ingebroken2: "ingebroken2",
  Kruis1: "kruis1",
  ManAutoLijnen: "man-auto-lijnen",
  Man: "man",
  Manogen: "manogen",
  Ogenman: "ogenman",
  Onemore: "onemore",
  Rits: "rits",
  Rodeman: "rodeman",
  Tekst: "tekst",
  UntitledArtwork94: "untitled-artwork-94",
  ViezeMan: "vieze-man",
  Viezevrouw: "viezevrouw",
  Vrouviezpsd: "vrouviezpsd",
  Womendoorgaan: "womendoorgaan",
  Youlikethis: "youlikethis"
} as const;

